export interface Theme {
  name: string
  label: string
  colors: Record<string, string>
}

export const themes: Theme[] = [
  {
    name: 'light',
    label: 'Light',
    colors: {
      'background': '#ffffff',
      'foreground': '#0f172a',
      'card': '#ffffff',
      'card-foreground': '#0f172a',
      'popover': '#ffffff',
      'popover-foreground': '#0f172a',
      'primary': '#FF5C00',
      'primary-foreground': '#ffffff',
      'secondary': '#f1f5f9',
      'secondary-foreground': '#0f172a',
      'muted': '#f1f5f9',
      'muted-foreground': '#64748b',
      'accent': '#f1f5f9',
      'accent-foreground': '#0f172a',
      'destructive': '#ef4444',
      'destructive-foreground': '#f8fafc',
      'border': '#e2e8f0',
      'input': '#e2e8f0',
      'ring': '#FF5C00',
    },
  },
  {
    name: 'dark',
    label: 'Dark',
    colors: {
      'background': '#0f172a',
      'foreground': '#f8fafc',
      'card': '#1e293b',
      'card-foreground': '#f8fafc',
      'popover': '#1e293b',
      'popover-foreground': '#f8fafc',
      'primary': '#FF5C00',
      'primary-foreground': '#ffffff',
      'secondary': '#1e293b',
      'secondary-foreground': '#f8fafc',
      'muted': '#1e293b',
      'muted-foreground': '#94a3b8',
      'accent': '#1e293b',
      'accent-foreground': '#f8fafc',
      'destructive': '#ef4444',
      'destructive-foreground': '#f8fafc',
      'border': '#1e293b',
      'input': '#1e293b',
      'ring': '#FF5C00',
    },
  },
  {
    name: 'orange',
    label: 'Orange',
    colors: {
      'background': '#ffffff',
      'foreground': '#0f172a',
      'card': '#ffffff',
      'card-foreground': '#0f172a',
      'popover': '#ffffff',
      'popover-foreground': '#0f172a',
      'primary': '#FF5C00',
      'primary-foreground': '#ffffff',
      'secondary': '#FFF3EB',
      'secondary-foreground': '#0f172a',
      'muted': '#FFF3EB',
      'muted-foreground': '#64748b',
      'accent': '#FFE5D6',
      'accent-foreground': '#0f172a',
      'destructive': '#ef4444',
      'destructive-foreground': '#f8fafc',
      'border': '#FFE5D6',
      'input': '#FFE5D6',
      'ring': '#FF5C00',
    },
  },
  {
    name: 'purple',
    label: 'Purple',
    colors: {
      'background': '#ffffff',
      'foreground': '#0f172a',
      'card': '#ffffff',
      'card-foreground': '#0f172a',
      'popover': '#ffffff',
      'popover-foreground': '#0f172a',
      'primary': '#8B5CF6',
      'primary-foreground': '#ffffff',
      'secondary': '#F3E8FF',
      'secondary-foreground': '#0f172a',
      'muted': '#F3E8FF',
      'muted-foreground': '#64748b',
      'accent': '#E9D5FF',
      'accent-foreground': '#0f172a',
      'destructive': '#ef4444',
      'destructive-foreground': '#f8fafc',
      'border': '#E9D5FF',
      'input': '#E9D5FF',
      'ring': '#8B5CF6',
    },
  },
  {
    name: 'green',
    label: 'Green',
    colors: {
      'background': '#ffffff',
      'foreground': '#0f172a',
      'card': '#ffffff',
      'card-foreground': '#0f172a',
      'popover': '#ffffff',
      'popover-foreground': '#0f172a',
      'primary': '#22C55E',
      'primary-foreground': '#ffffff',
      'secondary': '#F0FDF4',
      'secondary-foreground': '#0f172a',
      'muted': '#F0FDF4',
      'muted-foreground': '#64748b',
      'accent': '#DCFCE7',
      'accent-foreground': '#0f172a',
      'destructive': '#ef4444',
      'destructive-foreground': '#f8fafc',
      'border': '#DCFCE7',
      'input': '#DCFCE7',
      'ring': '#22C55E',
    },
  },
  {
    name: 'rose',
    label: 'Rose',
    colors: {
      'background': '#ffffff',
      'foreground': '#0f172a',
      'card': '#ffffff',
      'card-foreground': '#0f172a',
      'popover': '#ffffff',
      'popover-foreground': '#0f172a',
      'primary': '#F43F5E',
      'primary-foreground': '#ffffff',
      'secondary': '#FFF1F2',
      'secondary-foreground': '#0f172a',
      'muted': '#FFF1F2',
      'muted-foreground': '#64748b',
      'accent': '#FFE4E6',
      'accent-foreground': '#0f172a',
      'destructive': '#ef4444',
      'destructive-foreground': '#f8fafc',
      'border': '#FFE4E6',
      'input': '#FFE4E6',
      'ring': '#F43F5E',
    },
  },
]
